### ISSUE TITLE
Disk formatting blocked

### ISSUE THREAD

**Issue by arbulu89** [SUSE/drbd-formula#10]
Time to time the formula doesn't work because the `/dev/drbd` disk formatting get blocked and drbd is not setup properly.

Here the logs:
[drbr-error.log](https://github.com/SUSE/drbd-formula/files/3897489/drbr-error.log)

It happened already many times in the Azure cloud.

**Comment by nick-wang** [comment]
@arbulu89 I can't get useful information with the salt log, since it only shows drbd is not finished sync. Many reasons could lead this, do you still have the error environment running somewhere to access?

Or could you get the output of `drbdsetup status --verbose --statistics sapdata` and system log (or even hb_report) on both node?

**Comment by nick-wang** [comment]
@arbulu89 I am thinking is it caused by the old salt template render issue https://github.com/SUSE/drbd-formula/pull/11 you just fixed?

At least after upgrade with the 0.3.8, i succeed on deploy on SLE12SP4.

**Comment by arbulu89** [comment]
@nick-wang , No, this happened in SLE15. If I have the same scenario again, I will gather the logs you mention there (and If I can let the machine alive to give you access).
Thanks!

**Comment by arbulu89** [comment]
@nick-wang We have found this issue in other scenarios. So it's not nothing about the formula itself.
I'm closing the issue.
